name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
<<<<<<< HEAD
        runs-on: self-hosted
=======
        runs-on: ubuntu-latest
>>>>>>> d98d9f82f055ce00710293578d8ac2090afcf49b
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
<<<<<<< HEAD
        container: cuaesd/aesd-autotest:24-assignment7
        runs-on: self-hosted
=======
        container: cuaesd/aesd-autotest:24-assignment6
        runs-on: ubuntu-latest
>>>>>>> d98d9f82f055ce00710293578d8ac2090afcf49b
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
